# Outputting
permalink: /:categories/:title.html

# Conversion
markdown:         kramdown
highlighter:      rouge
excerpt_separator: <!--more-->

# Config for your profile.
title:            Chris Douglas - Elixir & Ruby Developer  # Site title
name:             Chris Douglas          # Your name
avatar:           /theme/img/avatar.jpg  # Path to an avatar image

baseurl: ""

# Add a directory to hold misc pages, just to keep the root directory clean.
include: ["_content"]

# Turn the work & gists into a collections.
collections_dir: _content
collections:
  work:
    output: true
    title: work
    permalink: /:collection/:title.html
  gists:
    output: true
    title: gists
    permalink: /collection/:title.html

defaults:
# Turn the profile sidebar on for all pages by default, except for the
# collections, where it is off and replaced by useful things on the sidebar.
# To override this one a page, use
#    show_profile: false
# to hide the profile.
  -
    scope:
      path: ""
    values:
      show_profile: true
  -
    scope:
      path: "list"
    values:
      show_profile: false
      layout: defaults/list
  -
    scope:
      path: "_posts"
    values:
      show_profile: false
      layout: defaults/post
  -
    scope:
      path: "_work"
    values:
      show_profile: false
      layout: defaults/work
  -
    scope:
      path: "_gists"
    values:
      show_profile: false
      layout: defaults/gist
